#!/bin/bash

# Setup script for Amazon Cognito configuration
# This script extracts Cognito configuration from CDK outputs and sets up environment variables

set -e

echo "🚀 Setting up Amazon Cognito configuration..."

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first."
    exit 1
fi

# Check if CDK is installed
if ! command -v cdk &> /dev/null; then
    echo "❌ AWS CDK is not installed. Please install it first."
    exit 1
fi

# Get the stack name (default to NoahInfrastructureStack)
STACK_NAME=${1:-NoahInfrastructureStack}

echo "📋 Getting CDK outputs for stack: $STACK_NAME"

# Get CDK outputs
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
CLIENT_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text)
IDENTITY_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='IdentityPoolId'].OutputValue" --output text)
BACKEND_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='BackendUrl'].OutputValue" --output text)
FRONTEND_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='FrontendUrl'].OutputValue" --output text)
AMPLIFY_APP_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='AmplifyAppUrl'].OutputValue" --output text 2>/dev/null || echo "")
AMPLIFY_DEV_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='AmplifyDevUrl'].OutputValue" --output text 2>/dev/null || echo "")

# Get AWS region
AWS_REGION=$(aws configure get region)

if [ -z "$AWS_REGION" ]; then
    AWS_REGION="us-east-1"
    echo "⚠️  No AWS region configured, defaulting to us-east-1"
fi

echo "✅ Retrieved Cognito configuration:"
echo "   User Pool ID: $USER_POOL_ID"
echo "   Client ID: $CLIENT_ID"
echo "   Identity Pool ID: $IDENTITY_POOL_ID"
echo "   AWS Region: $AWS_REGION"
echo "   Backend URL: $BACKEND_URL"
echo "   Frontend URL: $FRONTEND_URL"
if [ -n "$AMPLIFY_APP_URL" ]; then
    echo "   Amplify Main URL: $AMPLIFY_APP_URL"
fi
if [ -n "$AMPLIFY_DEV_URL" ]; then
    echo "   Amplify Dev URL: $AMPLIFY_DEV_URL"
fi

# Create frontend .env file
echo "📝 Creating frontend .env file..."
cat > frontend/.env << EOF
# AWS Cognito Configuration (Generated by setup-cognito.sh)
VITE_AWS_REGION=$AWS_REGION
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
VITE_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID
VITE_API_ENDPOINT=https://$BACKEND_URL

# API Configuration
VITE_API_BASE_URL=https://$BACKEND_URL/api

# Feature Flags
VITE_ENABLE_DISCOVERY_MODE=true
VITE_ENABLE_MULTILINGUAL=true

# UI Configuration
VITE_DEFAULT_LANGUAGE=english
VITE_MAX_MESSAGE_LENGTH=2000
VITE_TYPING_INDICATOR_DELAY=1000
EOF

# Create backend .env file
echo "📝 Creating backend .env file..."
cat > python-backend/.env << EOF
# AWS Cognito Configuration (Generated by setup-cognito.sh)
AWS_REGION=$AWS_REGION
COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_CLIENT_ID=$CLIENT_ID
COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID

# Database Configuration (will be set by ECS task definition)
# DATABASE_URL=postgresql://username:password@host:5432/noah

# OpenSearch Configuration (will be set by ECS task definition)
# OPENSEARCH_ENDPOINT=https://search-domain-endpoint

# API Configuration
CORS_ORIGINS=https://$FRONTEND_URL,http://localhost:5173,https://localhost:5173
EOF

echo "✅ Configuration files created successfully!"
echo ""
echo "📋 Next steps:"
echo "1. Update Cognito User Pool Client callback URLs to include: https://$FRONTEND_URL"
echo "2. Deploy your frontend and backend applications"
echo "3. Test the authentication flow"
echo ""
# Prepare callback URLs
CALLBACK_URLS="http://localhost:5173,https://localhost:5173"
LOGOUT_URLS="http://localhost:5173,https://localhost:5173"

if [ -n "$AMPLIFY_APP_URL" ]; then
    CALLBACK_URLS="$CALLBACK_URLS,$AMPLIFY_APP_URL"
    LOGOUT_URLS="$LOGOUT_URLS,$AMPLIFY_APP_URL"
fi

if [ -n "$AMPLIFY_DEV_URL" ]; then
    CALLBACK_URLS="$CALLBACK_URLS,$AMPLIFY_DEV_URL"
    LOGOUT_URLS="$LOGOUT_URLS,$AMPLIFY_DEV_URL"
fi

echo "🔧 To update callback URLs, run:"
echo "aws cognito-idp update-user-pool-client \\"
echo "  --user-pool-id $USER_POOL_ID \\"
echo "  --client-id $CLIENT_ID \\"
echo "  --callback-urls $CALLBACK_URLS \\"
echo "  --logout-urls $LOGOUT_URLS"